global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:8081']

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9092']